env:
    GH_TOKEN: "ENCRYPTED[0c32fb412da99036ea445fe0820659bd35048ea8237c599e145bed7ce53a132b17037b892a152bc18d1fad2f7790e000]"
    TG_TOKEN: "ENCRYPTED[240467d9411d49813d30e41759ccded951a388de865b20daf0b6f4723581df8ed5a5741e8200efbc75f9dc8825fcaa43]"
    TG_CHAT_ID: "ENCRYPTED[32bac2845a493c973ed1f3f1cb9b30f77c1b43e1f0297979c8469b34df1477207f28a7f07371ac0911a375ba4e581d56]"
    CIRRUS_WORKING_DIR: "/home/cirrus-ci-build"
    
task:
  name: "llvm building clang"
  timeout_in: 2h
  container:
      image: anggit86/docker:cirrus
      cpu: 8
      memory: 32G

  SSH_script:
       - mkdir -p -m 0700 /root/.ssh
       - cd /root/.ssh
       - curl $SSH_KEY -o id_rsa
       - curl $PUB_KEY -o id_rsa.pub
       - curl $KNOWN_HOSTS -o known_hosts

  Cone_witch_ssh_script:
       - git clone nfs86@git.pf.osdn.net:/gitroot/n/nf/nfs86/NFS-clang.git
